In [15]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

In [28]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import mean_squared_error, r2_score , mean_absolute_error

In [29]:
# load dataset 

df = pd.read_csv("../data/processed/preprocessed.csv")

X = df.drop("price", axis=1)
y = df["price"]

df

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,yr_built,lat,long,price
0,3,1.00,1180,5650,1.0,3,7,1955,47.5112,-122.257,221900.0
1,3,2.25,2570,7242,2.0,3,7,1951,47.7210,-122.319,538000.0
2,2,1.00,770,10000,1.0,3,6,1933,47.7379,-122.233,180000.0
3,4,3.00,1960,5000,1.0,5,7,1965,47.5208,-122.393,604000.0
4,3,2.00,1680,8080,1.0,3,8,1987,47.6168,-122.045,510000.0
...,...,...,...,...,...,...,...,...,...,...,...
21608,3,2.50,1530,1131,3.0,3,8,2009,47.6993,-122.346,360000.0
21609,4,2.50,2310,5813,2.0,3,8,2014,47.5107,-122.362,400000.0
21610,2,0.75,1020,1350,2.0,3,7,2009,47.5944,-122.299,402101.0
21611,3,2.50,1600,2388,2.0,3,8,2004,47.5345,-122.069,400000.0
21612,2,0.75,1020,1076,2.0,3,7,2008,47.5941,-122.299,325000.0

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [56]:
# Linear regression model 
 
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


lr_mae = mean_absolute_error(y_test, y_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
lr_r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error in Linear Regression: {lr_mae}")
print(f"Root Mean Squared Error in Linear Regression: {lr_rmse}")
print(f"R-squared in Linear Regression: {lr_r2}")

Mean Absolute Error in Linear Regression: 135355.64487532413
Root Mean Squared Error in Linear Regression: 230072.71262170593
R-squared in Linear Regression: 0.6498570956935908

In [33]:
# linear regression with StandardScaler

from sklearn.linear_model import LinearRegression
model_scaled = LinearRegression()

model_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = model_scaled.predict(X_test_scaled)


mse = mean_squared_error(y_test, y_pred_scaled)
r2 = r2_score(y_test, y_pred_scaled)

print(f"Mean Squared Error in Linear Regression with StandardScaler: {mse}")
print(f"R-squared in Linear Regression with StandardScaler: {r2}")

Mean Squared Error in Linear Regression with StandardScaler: 52933453093.113434
R-squared in Linear Regression with StandardScaler: 0.6498570956935688

In [57]:
# Ridge regression model

from sklearn.linear_model import Ridge
model = Ridge()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

ridge_mae = mean_absolute_error(y_test, y_pred)
ridge_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
ridge_r2 = r2_score(y_test, y_pred)

print("MAE in Ridge Regression:", ridge_mae)
print("RMSE in Ridge Regression:", ridge_rmse)
print("R2  in Ridge Regression:", ridge_r2)

MAE in Ridge Regression: 135352.23281422557
RMSE in Ridge Regression: 230073.33863165122
R2  in Ridge Regression: 0.6498551902678142

In [58]:
#  Lasso regression model

from sklearn.linear_model import Lasso

model = Lasso()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

lasso_mae = mean_absolute_error(y_test, y_pred)
lasso_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
lasso_r2 = r2_score(y_test, y_pred)

print("MAE in Lasso Regression:", lasso_mae)
print("RMSE in Lasso Regression:", lasso_rmse)
print("R2  in Lasso Regression:", lasso_r2)

MAE in Lasso Regression: 135355.16606404967
RMSE in Lasso Regression: 230072.77213678768
R2  in Lasso Regression: 0.6498569145440227

In [59]:
# ElasticNet Regression Model

from sklearn.linear_model import ElasticNet

model = ElasticNet()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

elastic_mae = mean_absolute_error(y_test, y_pred)
elastic_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
elastic_r2 = r2_score(y_test, y_pred)

print("MAE in ElasticNet Regression:", elastic_mae)
print("RMSE in ElasticNet Regression:", elastic_rmse)
print("R2  in ElasticNet Regression:", elastic_r2)

MAE in ElasticNet Regression: 133842.83461800157
RMSE in ElasticNet Regression: 248107.484996939
R2  in ElasticNet Regression: 0.5928121256737121

In [60]:
# Polynomial Regression Model

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)

model = LinearRegression()

model.fit(X_train_poly, y_train)

y_pred = model.predict(X_test_poly)

poly_mae = mean_absolute_error(y_test, y_pred)
poly_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
poly_r2 = r2_score(y_test, y_pred)

print("MAE in Polynomial Regression:", poly_mae)
print("RMSE in Polynomial Regression:", poly_rmse)
print("R2  in Polynomial Regression:", poly_r2)

MAE in Polynomial Regression: 115284.80754632269
RMSE in Polynomial Regression: 204008.56121400048
R2  in Polynomial Regression: 0.724696400475405

In [61]:
# support vector regression model

from sklearn.svm import SVR

model = SVR()

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

svr_mae = mean_absolute_error(y_test, y_pred)
svr_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
svr_r2 = r2_score(y_test, y_pred)

print("MAE in Support Vector Regression:", svr_mae)
print("RMSE in Support Vector Regression:", svr_rmse)
print("R2  in Support Vector Regression:", svr_r2)

MAE in Support Vector Regression: 229185.92895703143
RMSE in Support Vector Regression: 400861.1909828043
R2  in Support Vector Regression: -0.06292624067080332

In [46]:
# K-Nearest Neighbors Regression Model

from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor()

model.fit (X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

print("MAE in K-Nearest Neighbors Regression:", mean_absolute_error(y_test, y_pred))
print("RMSE in K-Nearest Neighbors Regression:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  in K-Nearest Neighbors Regression:", r2_score(y_test, y_pred))

MAE in K-Nearest Neighbors Regression: 98010.7560953042
RMSE in K-Nearest Neighbors Regression: 191301.81123754248
R2  in K-Nearest Neighbors Regression: 0.7579231454604907

In [63]:
# Decision Tree Regression Model

from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

dt_mae = mean_absolute_error(y_test, y_pred)
dt_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
dt_r2 = r2_score(y_test, y_pred)

print("MAE in Decision Tree Regression:", dt_mae)
print("RMSE in Decision Tree Regression:", dt_rmse)
print("R2  in Decision Tree Regression:", dt_r2)

MAE in Decision Tree Regression: 106252.65290307657
RMSE in Decision Tree Regression: 217373.36160486695
R2  in Decision Tree Regression: 0.6874440670788091

In [64]:
# Random Forest Regression Model

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

rf_mae = mean_absolute_error(y_test, y_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
rf_r2 = r2_score(y_test, y_pred)

print("MAE in Random Forest Regression:", rf_mae)
print("RMSE in Random Forest Regression:", rf_rmse)
print("R2  in Random Forest Regression:", rf_r2)

MAE in Random Forest Regression: 77955.86855455866
RMSE in Random Forest Regression: 167562.5376513083
R2  in Random Forest Regression: 0.8142756010168976

In [65]:
# Gradient Boosting Regression Model

from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

gb_mae = mean_absolute_error(y_test, y_pred)
gb_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
gb_r2 = r2_score(y_test, y_pred)

print("MAE in Gradient Boosting Regression:", gb_mae)
print("RMSE in Gradient Boosting Regression:", gb_rmse)
print("R2  in Gradient Boosting Regression:", gb_r2)

MAE in Gradient Boosting Regression: 87522.60653000075
RMSE in Gradient Boosting Regression: 170827.3076756184
R2  in Gradient Boosting Regression: 0.8069678284965028

In [66]:
# XGBoost Regression Model

from xgboost import XGBRegressor

model = XGBRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

xgb_mae = mean_absolute_error(y_test, y_pred)
xgb_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
xgb_r2 = r2_score(y_test, y_pred)

print("MAE in XGBoost Regression:", xgb_mae)
print("RMSE in XGBoost Regression:", xgb_rmse)
print("R2  in XGBoost Regression:", xgb_r2)

MAE in XGBoost Regression: 78382.55717239185
RMSE in XGBoost Regression: 162801.7957547817
R2  in XGBoost Regression: 0.824679183021593

In [67]:
# LightGBM Regression Model

from lightgbm import LGBMRegressor

model = LGBMRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

lgbm_mae = mean_absolute_error(y_test, y_pred)
lgbm_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
lgbm_r2 = r2_score(y_test, y_pred)

print("MAE in LightGBM Regression:", lgbm_mae)
print("RMSE in LightGBM Regression:", lgbm_rmse)
print("R2  in LightGBM Regression:", lgbm_r2)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001837 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1198
[LightGBM] [Info] Number of data points in the train set: 17290, number of used features: 10
[LightGBM] [Info] Start training from score 537768.047947
MAE in LightGBM Regression: 77608.5244505011
RMSE in LightGBM Regression: 154465.53754268365
R2  in LightGBM Regression: 0.8421740893014554

In [68]:
# CatBoost Regression Model

from catboost import CatBoostRegressor

model = CatBoostRegressor(random_state=42, verbose=0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

cat_mae = mean_absolute_error(y_test, y_pred)
cat_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
cat_r2 = r2_score(y_test, y_pred)

print("MAE in CatBoost Regression:", cat_mae)
print("RMSE in CatBoost Regression:", cat_rmse)
print("R2  in CatBoost Regression:", cat_r2)

MAE in CatBoost Regression: 73550.42318420728
RMSE in CatBoost Regression: 143389.99022303123
R2  in CatBoost Regression: 0.8639956578680758

In [69]:
# Voting Ensemble Regression

from sklearn.ensemble import VotingRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

model = VotingRegressor(
    estimators=[
        ("rf", RandomForestRegressor(random_state=42)),
        ("gb", GradientBoostingRegressor(random_state=42)),
        ("xgb", XGBRegressor(random_state=42)),
        ("cat", CatBoostRegressor(random_state=42, verbose=0))
    ]
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

voting_mae = mean_absolute_error(y_test, y_pred)
voting_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
voting_r2 = r2_score(y_test, y_pred)

print("MAE in Voting Ensemble Regression:", voting_mae)
print("RMSE in Voting Ensemble Regression:", voting_rmse)
print("R2  in Voting Ensemble Regression:", voting_r2)

MAE in Voting Ensemble Regression: 74359.61279769287
RMSE in Voting Ensemble Regression: 152269.11865982
R2  in Voting Ensemble Regression: 0.8466305811834007

In [54]:
# AdaBoost Regression Model

from sklearn.ensemble import AdaBoostRegressor

model = AdaBoostRegressor(random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MAE in AdaBoost Regression:", mean_absolute_error(y_test, y_pred))
print("RMSE in AdaBoost Regression:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2  in AdaBoost Regression:", r2_score(y_test, y_pred))

MAE in AdaBoost Regression: 269586.1264561931
RMSE in AdaBoost Regression: 320247.31234647194
R2  in AdaBoost Regression: 0.3215996066187288

In [70]:
# Final Model Comparison

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression",
        "ElasticNet Regression",
        "Polynomial Regression",
        "Decision Tree Regression",
        "Support Vector Regression",
        "Random Forest Regression",
        "Gradient Boosting Regression",
        "Voting Ensemble Regression",
        "XGBoost Regression",
        "LightGBM Regression",
        "CatBoost Regression"
    ],
    
    "MAE": [
        lr_mae,
        ridge_mae,
        lasso_mae,
        elastic_mae,
        poly_mae,
        dt_mae,
        svr_mae,
        rf_mae,
        gb_mae,
        voting_mae,
        xgb_mae,
        lgbm_mae,
        cat_mae
    ],
    
    "RMSE": [
        lr_rmse,
        ridge_rmse,
        lasso_rmse,
        elastic_rmse,
        poly_rmse,
        dt_rmse,
        svr_rmse,
        rf_rmse,
        gb_rmse,
        voting_rmse,
        xgb_rmse,
        lgbm_rmse,
        cat_rmse
    ],
    
    "R2": [
        lr_r2,
        ridge_r2,
        lasso_r2,
        elastic_r2,
        poly_r2,
        dt_r2,
        svr_r2,
        rf_r2,
        gb_r2,
        voting_r2,
        xgb_r2,
        lgbm_r2,
        cat_r2
    ]
})

results.sort_values("RMSE", ascending=True)

                           Model            MAE           RMSE        R2
12           CatBoost Regression   73550.423184  143389.990223  0.863996
9     Voting Ensemble Regression   74359.612798  152269.118660  0.846631
11           LightGBM Regression   77608.524451  154465.537543  0.842174
10            XGBoost Regression   78382.557172  162801.795755  0.824679
7       Random Forest Regression   77955.868555  167562.537651  0.814276
8   Gradient Boosting Regression   87522.606530  170827.307676  0.806968
4          Polynomial Regression  115284.807546  204008.561214  0.724696
5       Decision Tree Regression  106252.652903  217373.361605  0.687444
0              Linear Regression  135355.644875  230072.712622  0.649857
2               Lasso Regression  135355.166064  230072.772137  0.649857
1               Ridge Regression  135352.232814  230073.338632  0.649855
3          ElasticNet Regression  133842.834618  248107.484997  0.592812
6      Support Vector Regression  229185.928957  400861.190983 -0.062926

In [73]:
best_model = results.loc[results["RMSE"].idxmin()]

print("Best Model:", best_model["Model"])
print("Best RMSE:", best_model["RMSE"])
print("Best MAE:", best_model["MAE"])
print("Best R2:", best_model["R2"])

Best Model: CatBoost Regression
Best RMSE: 143389.99022303123
Best MAE: 73550.42318420728
Best R2: 0.8639956578680758

# BEST MODEL = CATBOOST REGRESSION